/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiRouteImport } from './routes/ai'
import { Route as ApiAiAskRouteImport } from './routes/api/ai-ask'
import { Route as NoteIdRouteImport } from './routes/note.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAskRoute = ApiAiAskRouteImport.update({
  id: '/api/ai-ask',
  path: '/api/ai-ask',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteIdRoute = NoteIdRouteImport.update({
  id: '/note/$id',
  path: '/note/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/api/ai-ask': typeof ApiAiAskRoute
  '/note/$id': typeof NoteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/api/ai-ask': typeof ApiAiAskRoute
  '/note/$id': typeof NoteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/api/ai-ask': typeof ApiAiAskRoute
  '/note/$id': typeof NoteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai' | '/api/ai-ask' | '/note/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai' | '/api/ai-ask' | '/note/$id'
  id: '__root__' | '/' | '/ai' | '/api/ai-ask' | '/note/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  ApiAiAskRoute: typeof ApiAiAskRoute
  NoteIdRoute: typeof NoteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-ask': {
      id: '/api/ai-ask'
      path: '/api/ai-ask'
      fullPath: '/api/ai-ask'
      preLoaderRoute: typeof ApiAiAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/$id': {
      id: '/note/$id'
      path: '/note/$id'
      fullPath: '/note/$id'
      preLoaderRoute: typeof NoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  ApiAiAskRoute: ApiAiAskRoute,
  NoteIdRoute: NoteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
